AirtBnB/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

config/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path("rooms/", include('rooms.urls', namespace="room")),
    path('users/', include('users.urls', namespace='user')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


handler404 = TemplateView.as_view(template_name='404.html')

core/urls.py
from django.urls import path
from rooms import views

app_name = 'core'

urlpatterns = [
    # path('', views.all_views, name='home'),
]

rooms/urls.py
from django.urls import path
from . import views


app_name = 'rooms'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<int:id>/', views.RoomDetailView.as_view(), name='detail'),
    path('search/', views.SearchView.as_view(), name='search'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{%endblock title%} | MADASS</title>
</head>

<body>
    <header>
        {% block search_bar %}
            <form method='get' action="{% url "rooms:search" %}">
                <input name='q' placeholder="Search">
            </form>
        {% endblock search_bar %}
        {% include "partials/header.html" %}
    </header>
    {%block content%}
    {%endblock content%}
    {% include "partials/footer.html" %}
</body>

</html>